export const LOONA_GROUP_ID = 1;

export const LOONA_ARTISTS = {
  HEEJIN: "HEEJIN",
  HYUNJIN: "HYUNJIN",
  HASEUL: "HASEUL",
  YEOJIN: "YEOJIN",
  VIVI: "VIVI",
  KIM_LIP: "KIM_LIP",
  JINSOUL: "JINSOUL",
  CHOERRY: "CHOERRY",
  YVES: "YVES",
  CHUU: "CHUU",
  GOWON: "GOWON",
  OLIVIA_HYE: "OLIVIA_HYE"
} as const;
